### PR TITLE
:bug: Fix version bumps in stable mode

### LINKED ISSUE #143: Cluster addon version gets bumped even if it shouldn't
/kind bug

**What steps did you take and what happened:**
The Clusteraddon version gets bumped if there was no change

**What did you expect to happen:**
The version of the cluster addons should remain the same if there was no change

### PR DESCRIPTION
**Pull request by janiskemper**
**What this PR does / why we need it**:
In stable mode, we don't want to bump the dependencies if we don't have to, i.e. cluster addons and node images.

For this, we compare the hashes. However, we forgot to set up the inputs to the functions that do that correctly and one value was empty.

**Which issue(s) this PR fixes**:
Fixes #143

**TODOs**:
- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

### CODE REVIEW

File: pkg/cmd/create.go [hunk 1]
```diff
@@ -152,6 +152,11 @@ func GetCreateOptions(ctx context.Context, clusterStackPath string) (*CreateOpti
 				return nil, fmt.Errorf("failed to download release asset: %w", err)
 			}
 
+			createOption.LatestReleaseHash, err = hash.ParseReleaseHash("./.tmp/release/hashes.json")
```
Comment (guettli) [inline pkg/cmd/create.go:155]: @janiskemper what happens if two csmctl commands run in parallel? Is it possible that one that there is a conflict?

Comment (janiskemper) [reply pkg/cmd/create.go:155]: yes there is. Can you open an issue for this? That goes beyond the scope of this PR.

Comment (guettli) [reply pkg/cmd/create.go:155]: @janiskemper here the new issue: https://github.com/SovereignCloudStack/csctl/issues/145

**Review by guettli — APPROVED** [review]
lgtm (except found, but unrelated issue).
